name: securepass-user
services:
  backend:
    build: ./backend
    image: 'securepass-user-be:1.1.0'
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=production
    restart: always

  frontend:
    build: ./frontend
    image: 'securepass-user-fe:1.1.0'
    ports:
      - '3001:80'
    depends_on:
      - backend
    restart: always